# Generated by Django 5.2.6 on 2025-09-21 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('patient_reg_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Patient registration number must be 3-20 alphanumeric characters', regex='^[A-Za-z0-9]{3,20}$')])),
                ('patient_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Patient name must have at least 3 characters', regex='^(?=.*[A-Za-z]).{3,}$')])),
                ('patient_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 6, 7, 8, or 9', regex='^[6-9]\\d{9}$')])),
                ('patient_dob', models.DateField()),
                ('doctor_verification_status', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Doctor Verification'), ('VERIFIED', 'Verified by Doctor'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING_VERIFICATION', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('INSURANCE', 'Insurance'), ('SPLIT', 'Split Payment')], max_length=15, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('case_sheet_notes', models.TextField(blank=True)),
                ('consultation_history', models.TextField(blank=True)),
                ('medicine_history', models.TextField(blank=True)),
                ('is_reported_to_admin', models.BooleanField(default=False)),
                ('admin_report_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_verified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bills', to=settings.AUTH_USER_MODEL)),
                ('prescribing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s_no', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('medicine_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Medicine code must be 6-20 alphanumeric characters with hyphens/underscores only', regex='^[A-Za-z0-9_-]{6,20}$')])),
                ('medicine_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Medicine name must have at least 3 characters with at least one letter', regex='^(?=.*[A-Za-z]).{3,}$')])),
                ('generic_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Generic name must have at least 3 characters with at least one letter', regex='^(?=.*[A-Za-z]).{3,}$')])),
                ('company_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Company name must have at least 2 characters with at least one letter', regex='^(?=.*[A-Za-z]).{2,}$')])),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('patient_reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 6, 7, 8, or 9', regex='^[6-9]\\d{9}$')])),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('consultation_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_doctors', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_created', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicines', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['s_no'],
            },
        ),
        migrations.CreateModel(
            name='BillMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dispensed_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dosage_instructions', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('doctor_approved', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True)),
                ('stock_reduced', models.BooleanField(default=False)),
                ('original_stock', models.PositiveIntegerField()),
                ('remaining_stock', models.PositiveIntegerField()),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_medicines', to='Pharmacist.bill')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='Pharmacist.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s_no', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('category_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Category name must have at least 3 characters with at least one letter', regex='^(?=.*[A-Za-z]).{3,}$')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
                'ordering': ['s_no'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Pharmacist.medicinecategory'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='Pharmacist__bill_nu_783145_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['patient_reg_number'], name='Pharmacist__patient_aa8084_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payment_status'], name='Pharmacist__payment_5084d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='Pharmacist__created_36678a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billmedicine',
            unique_together={('bill', 'medicine', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['s_no'], name='Pharmacist__s_no_7ebe46_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['medicine_code'], name='Pharmacist__medicin_353bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['medicine_name'], name='Pharmacist__medicin_b722fd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['patient_reg_number'], name='Pharmacist__patient_5fa578_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiry_date'], name='Pharmacist__expiry__30d9d1_idx'),
        ),
    ]
