# Generated by Django 5.2.6 on 2025-09-21 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySales',
            fields=[
                ('sales_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s_no', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=15)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='Pharmacist__payment_5084d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='Pharmacist__created_36678a_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='Pharmacist__medicin_b722fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='Pharmacist__patient_5fa578_idx',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='admin_report_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='case_sheet_notes',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='consultation_history',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='medicine_history',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='billmedicine',
            unique_together={('bill', 'medicine')},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='consultation_count',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='notify_doctors',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='patient_dob',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_reg_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Doctor Verification'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING_VERIFICATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacysales',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_sale', to='Pharmacist.bill'),
        ),
        migrations.AddField(
            model_name='pharmacysales',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysales',
            name='prescribing_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='original_stock',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='profit_amount',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='remaining_stock',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='stock_reduced',
        ),
        migrations.AddIndex(
            model_name='pharmacysales',
            index=models.Index(fields=['s_no'], name='Pharmacist__s_no_7262d1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysales',
            index=models.Index(fields=['sale_date'], name='Pharmacist__sale_da_9af7de_idx'),
        ),
    ]
