# Generated by Django 5.2.6 on 2025-10-23 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_staff_password'),
        ('Doctor', '0001_initial'),
        ('Pharmacist', '0001_initial'),
        ('Receptionist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bill',
            new_name='pharmacist__bill_nu_90ca34_idx',
            old_name='Pharmacist__bill_nu_783145_idx',
        ),
        migrations.RenameIndex(
            model_name='bill',
            new_name='pharmacist__patient_c71b39_idx',
            old_name='Pharmacist__patient_aa8084_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='pharmacist__s_no_af7951_idx',
            old_name='Pharmacist__s_no_7ebe46_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='pharmacist__medicin_63d32d_idx',
            old_name='Pharmacist__medicin_353bdd_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='pharmacist__expiry__518e3f_idx',
            old_name='Pharmacist__expiry__30d9d1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacysales',
            new_name='pharmacist__s_no_ab5a39_idx',
            old_name='Pharmacist__s_no_7262d1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacysales',
            new_name='pharmacist__sale_da_0ac526_idx',
            old_name='Pharmacist__sale_da_9af7de_idx',
        ),
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', help_text='Patient from Receptionist app', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bills', to='Receptionist.patient'),
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(blank=True, db_column='prescription_id', help_text="Link to doctor's prescription", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='Doctor.medicineprescription'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(db_column='bill_number', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_amount',
            field=models.DecimalField(db_column='discount_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor_verification_status',
            field=models.IntegerField(db_column='doctor_verification_status', default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor_verified_at',
            field=models.DateTimeField(blank=True, db_column='doctor_verified_at', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_reported_to_admin',
            field=models.IntegerField(db_column='is_reported_to_admin', default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(db_column='paid_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_column='paid_at', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_dob',
            field=models.DateField(db_column='patient_dob'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_name',
            field=models.CharField(db_column='patient_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_phone',
            field=models.CharField(db_column='patient_phone', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 6, 7, 8, or 9', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_reg_number',
            field=models.CharField(db_column='patient_reg_number', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], db_column='payment_method', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Doctor Verification'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_column='payment_status', default='PENDING_VERIFICATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pharmacist',
            field=models.ForeignKey(db_column='pharmacist_id', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='prescribing_doctor',
            field=models.ForeignKey(blank=True, db_column='prescribing_doctor_id', help_text='Doctor who prescribed from Authentication app', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_bills', to='Authentication.doctor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(db_column='subtotal', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(db_column='tax_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='bill',
            field=models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='bill_medicines', to='Pharmacist.bill'),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='discount_percent',
            field=models.DecimalField(db_column='discount_percent', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(db_column='dispensed_quantity', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='doctor_approved',
            field=models.IntegerField(db_column='doctor_approved', default=0),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='doctor_notes',
            field=models.TextField(blank=True, db_column='doctor_notes'),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='dosage_instructions',
            field=models.CharField(db_column='dosage_instructions', max_length=200),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='duration',
            field=models.CharField(db_column='duration', max_length=50),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='final_amount',
            field=models.DecimalField(db_column='final_amount', decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='frequency',
            field=models.CharField(db_column='frequency', max_length=50),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='medicine',
            field=models.ForeignKey(db_column='medicine_id', on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='Pharmacist.medicine'),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='prescribed_quantity',
            field=models.PositiveIntegerField(db_column='prescribed_quantity', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='total_price',
            field=models.DecimalField(db_column='total_price', decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billmedicine',
            name='unit_price',
            field=models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(db_column='batch_number', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Pharmacist.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(db_column='company_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(db_column='expiry_date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(db_column='generic_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.IntegerField(db_column='is_active', default=1),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(db_column='low_stock_threshold', default=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturing_date',
            field=models.DateField(db_column='manufacturing_date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.CharField(db_column='medicine_code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(db_column='medicine_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient_name',
            field=models.CharField(blank=True, db_column='patient_name', editable=False, help_text='DEPRECATED - Use Bill.patient instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient_phone',
            field=models.CharField(blank=True, db_column='patient_phone', editable=False, help_text='DEPRECATED - Use Bill.patient instead', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 6, 7, 8, or 9', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient_reg_number',
            field=models.CharField(blank=True, db_column='patient_reg_number', editable=False, help_text='DEPRECATED - Use Bill.patient instead', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescribed_by_doctor',
            field=models.ForeignKey(blank=True, db_column='prescribed_by_doctor_id', editable=False, help_text='DEPRECATED - Use Bill.prescribing_doctor instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(db_column='quantity', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='total_revenue',
            field=models.DecimalField(db_column='total_revenue', decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='total_sold',
            field=models.PositiveIntegerField(db_column='total_sold', default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='category_name',
            field=models.CharField(db_column='category_name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='created_by',
            field=models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='description',
            field=models.TextField(blank=True, db_column='description'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='is_active',
            field=models.IntegerField(db_column='is_active', default=1),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='bill',
            field=models.OneToOneField(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_sale', to='Pharmacist.bill'),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='patient_name',
            field=models.CharField(db_column='patient_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], db_column='payment_method', max_length=15),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='pharmacist',
            field=models.ForeignKey(db_column='pharmacist_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='prescribing_doctor',
            field=models.ForeignKey(blank=True, db_column='prescribing_doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_sales', to='Authentication.doctor'),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='sale_date',
            field=models.DateField(auto_now_add=True, db_column='sale_date'),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='total_amount',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacysales',
            name='total_items',
            field=models.PositiveIntegerField(db_column='total_items', default=0),
        ),
        migrations.AlterModelTable(
            name='bill',
            table='pharmacist_bill',
        ),
        migrations.AlterModelTable(
            name='billmedicine',
            table='pharmacist_billmedicine',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='pharmacist_medicine',
        ),
        migrations.AlterModelTable(
            name='medicinecategory',
            table='pharmacist_medicinecategory',
        ),
        migrations.AlterModelTable(
            name='pharmacysales',
            table='pharmacist_sales',
        ),
    ]
