# Generated by Django 5.2.6 on 2025-09-18 08:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DeptId', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('SpclId', models.AutoField(primary_key=True, serialize=False)),
                ('SpclName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('StaffName', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=10, unique=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('Address', models.TextField(max_length=100)),
                ('Experience', models.PositiveIntegerField(default=0)),
                ('Joining_Date', models.DateField(default=datetime.date.today)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist')], max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DocId', models.AutoField(primary_key=True, serialize=False)),
                ('Fee', models.DecimalField(decimal_places=3, max_digits=5)),
                ('DeptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.departments')),
                ('SpecializationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.specializations')),
                ('StaffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff')),
            ],
        ),
    ]
