# Generated by Django 5.2.6 on 2025-10-22 06:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(db_column='DeptId', primary_key=True, serialize=False)),
                ('dept_name', models.CharField(db_column='DeptName', max_length=25)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'authentication_departments',
                'ordering': ['dept_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('spcl_id', models.AutoField(db_column='SpclId', primary_key=True, serialize=False)),
                ('spcl_name', models.CharField(db_column='SpclName', max_length=20)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'db_table': 'authentication_specializations',
                'ordering': ['spcl_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(db_column='StaffId', primary_key=True, serialize=False)),
                ('staff_name', models.CharField(db_column='StaffName', max_length=20)),
                ('date_of_birth', models.DateField(db_column='DOB')),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('phone', models.CharField(db_column='Phone', max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], db_column='Gender', max_length=6)),
                ('address', models.TextField(db_column='Address')),
                ('experience', models.PositiveIntegerField(db_column='Experience')),
                ('joining_date', models.DateField(db_column='Joining_Date')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist')], db_column='Role', max_length=15)),
                ('is_active', models.IntegerField(db_column='IsActive')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'authentication_staff',
                'ordering': ['-staff_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(db_column='DocId', primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(db_column='Fee', decimal_places=3, help_text='Consultation fee in rupees', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.ForeignKey(db_column='DeptId_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Authentication.departments')),
                ('specialization', models.ForeignKey(db_column='SpecializationId_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Authentication.specializations')),
                ('staff', models.ForeignKey(db_column='StaffId_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profiles', to='Authentication.staff')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'authentication_doctor',
                'managed': True,
            },
        ),
    ]
