# Generated by Django 5.2.6 on 2025-10-22 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(db_column='Fee', decimal_places=2, help_text='Consultation fee in rupees', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
