# Generated by Django 5.2.6 on 2025-10-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, db_column='Password', max_length=255, null=True),
        ),
    ]
