# Generated by Django 5.2.6 on 2025-10-23 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.CharField(db_column='consultation_id', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('symptoms', models.TextField(db_column='symptoms')),
                ('diagnosis', models.TextField(db_column='diagnosis')),
                ('notes', models.TextField(blank=True, db_column='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('is_active', models.IntegerField(db_column='is_active', default=1)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', help_text='Optional link to appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='Receptionist.appointment')),
                ('doctor', models.ForeignKey(db_column='doctor_id', help_text='Doctor from Authentication app', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Authentication.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', help_text='Patient from Receptionist app', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Receptionist.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'doctor_consultation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('prescription_id', models.CharField(db_column='prescription_id', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('medicine_name', models.CharField(blank=True, db_column='medicine_name', help_text='Name of medicine prescribed', max_length=200)),
                ('dosage', models.CharField(blank=True, db_column='dosage', help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(blank=True, db_column='frequency', help_text='e.g., 3 times daily', max_length=100)),
                ('duration_days', models.IntegerField(blank=True, db_column='duration_days', help_text='Duration in days', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending at Pharmacy'), ('partial', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_column='fulfillment_status', default='pending', help_text='Pharmacy fulfillment status', max_length=20)),
                ('dispensed_quantity', models.IntegerField(blank=True, db_column='dispensed_quantity', help_text='Actual quantity dispensed by pharmacist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('is_active', models.IntegerField(db_column='is_active', default=1)),
                ('consultation', models.ForeignKey(db_column='consultation_id', help_text='Link to consultation record', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Doctor.consultation')),
            ],
            options={
                'verbose_name': 'Medicine Prescription',
                'verbose_name_plural': 'Medicine Prescriptions',
                'db_table': 'doctor_medicineprescription',
                'ordering': ['-created_at'],
            },
        ),
    ]
