# Generated by Django 5.2.6 on 2025-10-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_staff_password'),
        ('Doctor', '0001_initial'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='appointmentid', help_text='Optional link to appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='Receptionist.appointment'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultation_id',
            field=models.CharField(db_column='consultationid', editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(db_column='doctorid', help_text='Doctor from Authentication app', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Authentication.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='patientid', help_text='Patient from Receptionist app', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Receptionist.patient'),
        ),
    ]
