# Generated by Django 5.2.6 on 2025-10-24 06:16

import Receptionist.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_staff_password'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_column='appointment_date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(db_column='appointment_id', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_appointments', to='Authentication.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Receptionist.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(db_column='reason'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('phone_booked', 'Phone Booked'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_column='status', default='phone_booked', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(db_column='token_number'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Receptionist.appointment'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(db_column='bill_number', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('renewal', 'Renewal Fee'), ('consultation', 'Consultation Fee')], db_column='bill_type', max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_amount',
            field=models.DecimalField(db_column='discount_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='final_amount',
            field=models.DecimalField(db_column='final_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_column='paid_at', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('online', 'Online')], db_column='payment_mode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_column='payment_status', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='registration',
            field=models.ForeignKey(blank=True, db_column='registration_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Receptionist.registration'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='Receptionist.bill'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.CharField(db_column='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('consultation', 'Consultation'), ('procedure', 'Procedure')], db_column='item_type', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(db_column='address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_column='blood_group', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(db_column='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(db_column='full_name', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_reg_number',
            field=models.CharField(db_column='patient_reg_number', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='expiry_date',
            field=models.DateField(blank=True, db_column='expiry_date', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fee_amount',
            field=models.DecimalField(db_column='fee_amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='patient',
            field=models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='Receptionist.patient'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(db_column='registration_date', default=Receptionist.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('initial', 'Initial Registration'), ('renewal', 'Renewal')], db_column='registration_type', default='initial', max_length=10),
        ),
    ]
