# Generated by Django 5.2.6 on 2025-09-18 09:08

import Receptionist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(default=Receptionist.models.get_today_date),
        ),
    ]
