# Generated by Django 5.2.6 on 2025-09-18 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0002_alter_registration_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Name should have at least three characters')]),
        ),
    ]
