# Generated by Django 5.2.6 on 2025-09-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0003_alter_patient_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='Receptionis_created_39a6d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='Receptionis_bill_nu_07f49f_idx',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('registration', 'Registration Only'), ('consultation', 'Consultation Only'), ('combined', 'Registration + Consultation')], default='combined', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Receptionist.registration'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Receptionist.appointment'),
        ),
    ]
