# Generated by Django 5.2.6 on 2025-09-18 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0004_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('registration', 'Registration Only'), ('registration_consultation', 'Registration + Consultation'), ('renewal', 'Renewal Only'), ('renewal_consultation', 'Renewal + Consultation'), ('consultation', 'Consultation Only')], default='consultation', max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
