# Generated by Django 5.2.6 on 2025-09-18 11:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0005_alter_doctor_options_alter_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='Date of birth cannot be in the future.')]),
        ),
    ]
